name: Push Trigger Workflow

### Executa apenas em push
on:
  push:
    branches: 
      - main
      - develop
    paths:
      - 'src/**' # CRIAR ESSES ARQUIVOS PARA FUNCIONAR --> SO FUNCIONA SE TIVER MODIFICAÇÕES EM ARQUIVOS DESSA PASTA
      - 'README.md' # CRIAR ESSES ARQUIVOS PARA FUNCIONAR --> SO FUNCIONA SE TIVER MODIFICAÇÕES NESSE ARQUIVO

jobs:
  push-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Informações do Push
      run: |
        echo "Workflow disparado por PUSH"
        echo "Commit: ${{ github.sha }}"
        echo "Autor: ${{ github.actor }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Repositório: ${{ github.repository }}"
    
    - name: Listar arquivos modificados
      run: |
        echo "Arquivos no repositório:"
        ls -la