name: Hello GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Executar Hello world
      run: echo "Hello, GitHub Actions!"

    - name: Mostrar informações do sistema
      run: |
        echo "Sistema Operacional: ${{ runner.os }}"
        echo "Diretório atual: $(pwd)"
        echo "Data Atual: $(date)"
        echo "Usuário: $(whoami)"
        
    - name: Listar arquivos do repositorio
      run: ls -la

    - name: Comandos Múltiplos
      run: |
        echo "Este é o primeiro lab para treinar o aprendizado de GitHub Actions."
        echo "Workflow executado com sucesso"
        echo "Pronto para o próximo passo!"